//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.ESB.RabbitMq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RabbitMqResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RabbitMqResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.ESB.RabbitMq.RabbitMqResources", typeof(RabbitMqResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account ({0}) the process is running under does not have permission to access queue &apos;{1}&apos;.  Permissions required on queue: Send, Receive, and Peek.  This instance will now close..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only local queues can be created.  Remote queue &apos;{0}&apos; not created..
        /// </summary>
        internal static string CannotCreateRemoteQueue {
            get {
                return ResourceManager.GetString("CannotCreateRemoteQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only local queues can be dropped.  Remote queue &apos;{0}&apos; not dropped..
        /// </summary>
        internal static string CannotDropRemoteQueue {
            get {
                return ResourceManager.GetString("CannotDropRemoteQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to dequeue rabbitMq queue &apos;{0}&apos;.  Exception: {1}.
        /// </summary>
        internal static string DequeueError {
            get {
                return ResourceManager.GetString("DequeueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to dequeue message with id &apos;{0}&apos; from rabbitMq queue &apos;{1}&apos;.  Exception: {2}.
        /// </summary>
        internal static string DequeueMessageIdError {
            get {
                return ResourceManager.GetString("DequeueMessageIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to establish existence of queue &apos;{0}&apos; (path &apos;{1}&apos;).  Exception: {2}.
        /// </summary>
        internal static string ExistsError {
            get {
                return ResourceManager.GetString("ExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to read top {0} messages from rabbitMq queue &apos;{1}&apos;.  Exception: {2}.
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to remove message id &apos;{0}&apos; from rabbitMq queue &apos;{1}&apos;.  Exception: {2}.
        /// </summary>
        internal static string RemoveError {
            get {
                return ResourceManager.GetString("RemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to send message data on rabbitMq queue &apos;{0}&apos;.  Exception: {1}.
        /// </summary>
        internal static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to send message with id &apos;{0}&apos; on rabbitMq queue &apos;{1}&apos;.  Exception: {2}.
        /// </summary>
        internal static string SendMessageIdError {
            get {
                return ResourceManager.GetString("SendMessageIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
