//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Management.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Management.Messages.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain message type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotObtainMessageType {
            get {
                return ResourceManager.GetString("CannotObtainMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the selected message(s).  Continue?.
        /// </summary>
        internal static string ConfirmMessageDeletion {
            get {
                return ResourceManager.GetString("ConfirmMessageDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove message with id &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotRemoveMessage {
            get {
                return ResourceManager.GetString("CouldNotRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with id &apos;{0}&apos; has been enqueued on queue &apos;{1}&apos;..
        /// </summary>
        internal static string EnqueuedMessage {
            get {
                return ResourceManager.GetString("EnqueuedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_ArrowBack {
            get {
                object obj = ResourceManager.GetObject("Image_ArrowBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Messages {
            get {
                object obj = ResourceManager.GetObject("Image_Messages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_StopIgnoring {
            get {
                object obj = ResourceManager.GetObject("Image_StopIgnoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display message with id &apos;{0}&apos; since it is compressed..
        /// </summary>
        internal static string MessageCompressed {
            get {
                return ResourceManager.GetString("MessageCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display message with id &apos;{0}&apos; since it is encrypted..
        /// </summary>
        internal static string MessageEncrypted {
            get {
                return ResourceManager.GetString("MessageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transport message assembly qualified type name &apos;{0}&apos; does not exactly match the type returned by the .NET runtime &apos;{1}&apos;..
        /// </summary>
        internal static string MessageTypeMismatch {
            get {
                return ResourceManager.GetString("MessageTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages have been selected..
        /// </summary>
        internal static string NoMessagesSelected {
            get {
                return ResourceManager.GetString("NoMessagesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serializer type has been specified. The DefaultSerializer will be used..
        /// </summary>
        internal static string NoSerializerDefaultSerializer {
            get {
                return ResourceManager.GetString("NoSerializerDefaultSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed message with id &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string RemovedMessage {
            get {
                return ResourceManager.GetString("RemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer type &apos;{0}&apos; could not be created. The DefaultSerializer will be used.  Exception reported: {1].
        /// </summary>
        internal static string SerializerTypeExceptionDefaultSerializer {
            get {
                return ResourceManager.GetString("SerializerTypeExceptionDefaultSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the IQueueReader for the queue represented by the source queue uri..
        /// </summary>
        internal static string SourceQueueUriReader {
            get {
                return ResourceManager.GetString("SourceQueueUriReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with id &apos;{0}&apos; is no longer being ignored..
        /// </summary>
        internal static string StoppedIgnoringMessage {
            get {
                return ResourceManager.GetString("StoppedIgnoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Text_Messages {
            get {
                return ResourceManager.GetString("Text_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh messages.
        /// </summary>
        internal static string Text_RefreshMessages {
            get {
                return ResourceManager.GetString("Text_RefreshMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh queues.
        /// </summary>
        internal static string Text_RefreshQueues {
            get {
                return ResourceManager.GetString("Text_RefreshQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to source queue.
        /// </summary>
        internal static string Text_ReturnToSourceQueue {
            get {
                return ResourceManager.GetString("Text_ReturnToSourceQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop ignoring.
        /// </summary>
        internal static string Text_StopIgnoring {
            get {
                return ResourceManager.GetString("Text_StopIgnoring", resourceCulture);
            }
        }
    }
}
