//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Management.Shell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Management.Shell.ManagementResources", typeof(ManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting creation of data store repository from type &apos;{0}&apos;..
        /// </summary>
        public static string AttemptCreationOfDataStoreRepository {
            get {
                return ResourceManager.GetString("AttemptCreationOfDataStoreRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting creation of queue repository from type &apos;{0}&apos;..
        /// </summary>
        public static string AttemptCreationOfQueueRepository {
            get {
                return ResourceManager.GetString("AttemptCreationOfQueueRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove the selected &apos;{0}&apos;.  Continue?.
        /// </summary>
        public static string ConfirmRemoval {
            get {
                return ResourceManager.GetString("ConfirmRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create datastore repository from type &apos;{0}&apos;.  Exception reported: {1}.
        /// </summary>
        public static string DataStoreRepositoryCreationException {
            get {
                return ResourceManager.GetString("DataStoreRepositoryCreationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data store repository successfully created from type &apos;{0}&apos;..
        /// </summary>
        public static string DataStoreRepositoryCreationSuccessful {
            get {
                return ResourceManager.GetString("DataStoreRepositoryCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data store repository is required for component &apos;{0}&apos; to function..
        /// </summary>
        public static string DataStoreRepositoryRequired {
            get {
                return ResourceManager.GetString("DataStoreRepositoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find DataStoreRepositoryType &apos;{0}&apos; as specified in the application configuration..
        /// </summary>
        public static string DataStoreRepositoryTypeNotFound {
            get {
                return ResourceManager.GetString("DataStoreRepositoryTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy HH:mm:ss.
        /// </summary>
        public static string FormatDateTime {
            get {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Image_Add {
            get {
                object obj = ResourceManager.GetObject("Image_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_ArrowDown {
            get {
                object obj = ResourceManager.GetObject("Image_ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DataStores {
            get {
                object obj = ResourceManager.GetObject("Image_DataStores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DriveMagnify {
            get {
                object obj = ResourceManager.GetObject("Image_DriveMagnify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Filter {
            get {
                object obj = ResourceManager.GetObject("Image_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Queues {
            get {
                object obj = ResourceManager.GetObject("Image_Queues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_RefreshSmall {
            get {
                object obj = ResourceManager.GetObject("Image_RefreshSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Remove {
            get {
                object obj = ResourceManager.GetObject("Image_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Save {
            get {
                object obj = ResourceManager.GetObject("Image_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox work queue uri.
        /// </summary>
        public static string InboxWorkQueueUri {
            get {
                return ResourceManager.GetString("InboxWorkQueueUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; implementing IManagementModule has no default constructor.  It cannot be instantiated..
        /// </summary>
        public static string ManagementModuleInitializerHasNoDefaultConstructor {
            get {
                return ResourceManager.GetString("ManagementModuleInitializerHasNoDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data store repository available.  Please check the log for the reason..
        /// </summary>
        public static string NoDataStoreRepositoryAvailable {
            get {
                return ResourceManager.GetString("NoDataStoreRepositoryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data store repository type specified.  Add an appSetting with name &apos;DataStoreRepositoryType&apos; and specify the type name or assembly qualified name in the value..
        /// </summary>
        public static string NoDataStoreRepositoryTypeSpecified {
            get {
                return ResourceManager.GetString("NoDataStoreRepositoryTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data store has been selected..
        /// </summary>
        public static string NoDataStoreSelected {
            get {
                return ResourceManager.GetString("NoDataStoreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; selected..
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no queue repository available.  Please check the log for the reason..
        /// </summary>
        public static string NoQueueRepositoryAvailable {
            get {
                return ResourceManager.GetString("NoQueueRepositoryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queue repository type specified.  Add an appSetting with name &apos;QueueRepositoryType&apos; and specify the type name or assembly qualified name in the value..
        /// </summary>
        public static string NoQueueRepositoryTypeSpecified {
            get {
                return ResourceManager.GetString("NoQueueRepositoryTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create queue repository from type &apos;{0}&apos;.  Exception reported: {1}.
        /// </summary>
        public static string QueueRepositoryCreationException {
            get {
                return ResourceManager.GetString("QueueRepositoryCreationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue repository successfully created from type &apos;{0}&apos;..
        /// </summary>
        public static string QueueRepositoryCreationSuccessful {
            get {
                return ResourceManager.GetString("QueueRepositoryCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find QueueRepositoryType &apos;{0}&apos; as specified in the application configuration..
        /// </summary>
        public static string QueueRepositoryTypeNotFound {
            get {
                return ResourceManager.GetString("QueueRepositoryTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running task &apos;{0}&apos;..
        /// </summary>
        public static string RunningTask {
            get {
                return ResourceManager.GetString("RunningTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has been completed..
        /// </summary>
        public static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has been queued..
        /// </summary>
        public static string TaskQueued {
            get {
                return ResourceManager.GetString("TaskQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        public static string Text_CheckAll {
            get {
                return ResourceManager.GetString("Text_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stores.
        /// </summary>
        public static string Text_DataStores {
            get {
                return ResourceManager.GetString("Text_DataStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert checks.
        /// </summary>
        public static string Text_InvertChecks {
            get {
                return ResourceManager.GetString("Text_InvertChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Text_Move {
            get {
                return ResourceManager.GetString("Text_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queues.
        /// </summary>
        public static string Text_Queues {
            get {
                return ResourceManager.GetString("Text_Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Text_Refresh {
            get {
                return ResourceManager.GetString("Text_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh data stores.
        /// </summary>
        public static string Text_RefreshDataStores {
            get {
                return ResourceManager.GetString("Text_RefreshDataStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Text_Remove {
            get {
                return ResourceManager.GetString("Text_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Text_Save {
            get {
                return ResourceManager.GetString("Text_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; may not be empty..
        /// </summary>
        public static string ValueMayNotBeEmpty {
            get {
                return ResourceManager.GetString("ValueMayNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not return a valid UserControl instance.  ViewUserControl is &apos;null&apos;..
        /// </summary>
        public static string ViewUserControlNull {
            get {
                return ResourceManager.GetString("ViewUserControlNull", resourceCulture);
            }
        }
    }
}
