//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.ESB.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ESBResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ESBResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.ESB.Core.ESBResources", typeof(ESBResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find assembly &apos;{0}&apos; during operation &apos;{1}&apos;..
        /// </summary>
        public static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to purge queue &apos;{0}&apos; but the queue does not implement the IPurge interface.  The queue cannot be purged..
        /// </summary>
        public static string CannotPurgeQueue {
            get {
                return ResourceManager.GetString("CannotPurgeQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMessageSerializer implementation &apos;{0}&apos; does not implement IKnownTypes.  There are {1} known type assemblies specified in the application configuration that cannot be registered..
        /// </summary>
        public static string CannotRegisterKnownTypes {
            get {
                return ResourceManager.GetString("CannotRegisterKnownTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression algorithm &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string CompressionAlgorithmException {
            get {
                return ResourceManager.GetString("CompressionAlgorithmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve instance (or default instance) of type &apos;{0}&apos; with key &apos;{0}&apos;..
        /// </summary>
        public static string CouldNotResolveKeyException {
            get {
                return ResourceManager.GetString("CouldNotResolveKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve instance (or default instance) of type &apos;{0}&apos;..
        /// </summary>
        public static string CouldNotResolveTypeException {
            get {
                return ResourceManager.GetString("CouldNotResolveTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [worker available ({0})] worker inbox = {1} / distributor control inbox = {2}.
        /// </summary>
        public static string DebugWorkerAvailable {
            get {
                return ResourceManager.GetString("DebugWorkerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; has no default constructor..
        /// </summary>
        public static string DefaultConstructorRequired {
            get {
                return ResourceManager.GetString("DefaultConstructorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the DeferredMessageProcessor should be created.  Check that the ProcessorThreadPool for the DeferredMessageProcessorFactory is not using more than 1 thread..
        /// </summary>
        public static string DeferredMessageProcessorInstanceException {
            get {
                return ResourceManager.GetString("DeferredMessageProcessorInstanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream dequeued from queue &apos;{0}&apos;..
        /// </summary>
        public static string DequeueStream {
            get {
                return ResourceManager.GetString("DequeueStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using the distributor a control inbox is required to receive notifications of worker availability.  No control inbox has been configured..
        /// </summary>
        public static string DistributorRequiresControlInbox {
            get {
                return ResourceManager.GetString("DistributorRequiresControlInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subscription manager is being used but, as per configuration, no subscriptions will be automatically registered..
        /// </summary>
        public static string DoNotRegisterSubscriptions {
            get {
                return ResourceManager.GetString("DoNotRegisterSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default service has already been registered for type &apos;{0}&apos;..
        /// </summary>
        public static string DuplicateDefaultServiceType {
            get {
                return ResourceManager.GetString("DuplicateDefaultServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A queue factory for scheme &apos;{0}&apos; already existed.  Removed queue factory type &apos;{1}&apos; to register queue factory type &apos;{2}&apos;..
        /// </summary>
        public static string DuplicateQueueFactoryReplaced {
            get {
                return ResourceManager.GetString("DuplicateQueueFactoryReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service has already been registered for type &apos;{0}&apos;..
        /// </summary>
        public static string DuplicateServiceTypeException {
            get {
                return ResourceManager.GetString("DuplicateServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application configuration contains a &apos;durationToIgnoreOnFailure&apos; with invalid items &apos;{0}&apos;..
        /// </summary>
        public static string DurationToIgnoreOnFailureFormatError {
            get {
                return ResourceManager.GetString("DurationToIgnoreOnFailureFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption algorithm &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string EncryptionAlgorithmException {
            get {
                return ResourceManager.GetString("EncryptionAlgorithmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type &apos;{0}&apos; with id &apos;{1}&apos; equeuing on queue &apos;{2}&apos;..
        /// </summary>
        public static string EnqueueMessage {
            get {
                return ResourceManager.GetString("EnqueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enqueue data of type &apos;{0}&apos; on queue &apos;{1}&apos; since expected type is &apos;{2}&apos;..
        /// </summary>
        public static string EnqueueMessageDataTypeMismatchException {
            get {
                return ResourceManager.GetString("EnqueueMessageDataTypeMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a fatal exception accessing the idempotence service type &apos;{0}&apos;.  Without the idempotence service operational the integrity of the message processing cannot be guaranteed.  The pipeline has been aborted.  Exception: {1}.
        /// </summary>
        public static string FatalIdempotenceServiceException {
            get {
                return ResourceManager.GetString("FatalIdempotenceServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy HH:mm:ss.
        /// </summary>
        public static string FormatDateFull {
            get {
                return ResourceManager.GetString("FormatDateFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [configuration] : state folder = &apos;{0}&apos;.
        /// </summary>
        public static string InformationStateFolder {
            get {
                return ResourceManager.GetString("InformationStateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only scheme &apos;{0}&apos; is supported.  The given uri &apos;{1}&apos; is not supported..
        /// </summary>
        public static string InvalidSchemeException {
            get {
                return ResourceManager.GetString("InvalidSchemeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided xml is not of type Shuttle.ESB.Core.TransportMessage..
        /// </summary>
        public static string MessageDeserializationException {
            get {
                return ResourceManager.GetString("MessageDeserializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type &apos;{0}&apos; with id &apos;{1}&apos; has been deserialized..
        /// </summary>
        public static string MessageDeserialized {
            get {
                return ResourceManager.GetString("MessageDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message handler type &apos;{0}&apos; raised exception &apos;{1}&apos;.  Message type &apos;{2}&apos; with id &apos;{3}&apos; has reached the maximum number of retries ({4}).  The message has been moved to error queue &apos;{5}&apos;.
        /// </summary>
        public static string MessageHandlerExceptionFailure {
            get {
                return ResourceManager.GetString("MessageHandlerExceptionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message handler type &apos;{0}&apos; raised exception &apos;{1}&apos;.  Handling of message type &apos;{2}&apos; with id &apos;{3}&apos; will be retried.  It is retry number: {4} / {5}.
        /// </summary>
        public static string MessageHandlerExceptionWillRetry {
            get {
                return ResourceManager.GetString("MessageHandlerExceptionWillRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type &apos;{0}&apos; with id &apos;{1}&apos; invoking on handler &apos;{2}&apos;..
        /// </summary>
        public static string MessageHandlerInvoke {
            get {
                return ResourceManager.GetString("MessageHandlerInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No handler has been registered for message type &apos;{0}&apos;.  The message (id &apos;{1}&apos;) has been moved to error queue &apos;{2}&apos;..
        /// </summary>
        public static string MessageNotHandledFailure {
            get {
                return ResourceManager.GetString("MessageNotHandledFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No handler has been registered for message type &apos;{0}&apos;.  The message (id &apos;{1}&apos;) has been ignored..
        /// </summary>
        public static string MessageNotHandledIgnored {
            get {
                return ResourceManager.GetString("MessageNotHandledIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message of type &apos;{0}&apos; has been routed to more than one endpoint: {1}.
        /// </summary>
        public static string MessageRoutedToMoreThanOneEndpoint {
            get {
                return ResourceManager.GetString("MessageRoutedToMoreThanOneEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route could be found for message of type &apos;{0}&apos;..
        /// </summary>
        public static string MessageRouteNotFound {
            get {
                return ResourceManager.GetString("MessageRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While transferring message from queue with uri &apos;{0}&apos; to queue with uri &apos;{1}&apos; an exception &apos;{2}&apos; occurred.  Message type &apos;{3}&apos; with id &apos;{4}&apos; has reached the maximum number of retries ({5}).  The message has been moved to error queue &apos;{6}&apos;.
        /// </summary>
        public static string MessageTransferExceptionFailure {
            get {
                return ResourceManager.GetString("MessageTransferExceptionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While transferring message from queue with uri &apos;{0}&apos; to queue with uri &apos;{1}&apos; an exception &apos;{2}&apos; occurred.  Transfer of message type &apos;{3}&apos; with id &apos;{4}&apos; will be retried.  It is retry number: {5}.
        /// </summary>
        public static string MessageTransferExceptionWillRetry {
            get {
                return ResourceManager.GetString("MessageTransferExceptionWillRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IDeferredMessageQueue implementation has been specified..
        /// </summary>
        public static string NoDeferredMessageQueue {
            get {
                return ResourceManager.GetString("NoDeferredMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IIdempotenceService implementation has been specified..
        /// </summary>
        public static string NoIdempotenceService {
            get {
                return ResourceManager.GetString("NoIdempotenceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inbox has been specified so no subscriptions can be registered since event message types subscribed to are sent to the inbox of the subscriber..
        /// </summary>
        public static string NoInboxForSubscriptions {
            get {
                return ResourceManager.GetString("NoInboxForSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queues have been specified for the bus; it cannot start.  Please specify either an inbox / distributor configuration (to process messages) or an outbox configuration (to send/publish messages) or both..
        /// </summary>
        public static string NoQueuesConfigurationException {
            get {
                return ResourceManager.GetString("NoQueuesConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscription manager has been specified..
        /// </summary>
        public static string NoSubscriptionManager {
            get {
                return ResourceManager.GetString("NoSubscriptionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;{0}&apos; does not implement interface &apos;{1}&apos;..
        /// </summary>
        public static string NotImplementedOnQueue {
            get {
                return ResourceManager.GetString("NotImplementedOnQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory that creates pipelines for context type &apos;{0}&apos; has no create method..
        /// </summary>
        public static string PipelineFactoryHasNoCreateMethod {
            get {
                return ResourceManager.GetString("PipelineFactoryHasNoCreateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pipeline factory has been registered for context type &apos;{0}&apos;..
        /// </summary>
        public static string PipelineFactoryNotFound {
            get {
                return ResourceManager.GetString("PipelineFactoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler type &apos;{0}&apos; does not have the requires ProcessMessage method that handles message type &apos;{1}&apos;..
        /// </summary>
        public static string ProcessMessageMethodMissingException {
            get {
                return ResourceManager.GetString("ProcessMessageMethodMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging inbox work queue &apos;{0}&apos;..
        /// </summary>
        public static string PurgingInboxWorkQueue {
            get {
                return ResourceManager.GetString("PurgingInboxWorkQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging inbox work queue &apos;{0}&apos; complete..
        /// </summary>
        public static string PurgingInboxWorkQueueComplete {
            get {
                return ResourceManager.GetString("PurgingInboxWorkQueueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;{0}&apos; has not been specified in the configuration..
        /// </summary>
        public static string QueueConfigurationException {
            get {
                return ResourceManager.GetString("QueueConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue with uri &apos;{0}&apos; does not exist..
        /// </summary>
        public static string QueueDoesNotExistException {
            get {
                return ResourceManager.GetString("QueueDoesNotExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queue factory has been registered for scheme &apos;{0}&apos;..
        /// </summary>
        public static string QueueFactoryNotFoundException {
            get {
                return ResourceManager.GetString("QueueFactoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue factory type &apos;{0}&apos; not found.  Cannot create queue factory for scheme &apos;{1}&apos;..
        /// </summary>
        public static string QueueFactoryTypeNotFoundException {
            get {
                return ResourceManager.GetString("QueueFactoryTypeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueueTransactionScope (&apos;{0}&apos;) using ambient transaction..
        /// </summary>
        public static string QueueTransactionScopeAmbient {
            get {
                return ResourceManager.GetString("QueueTransactionScopeAmbient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueueTransactionScope (&apos;{0}&apos;) using ambient transaction has completed..
        /// </summary>
        public static string QueueTransactionScopeAmbientCompleted {
            get {
                return ResourceManager.GetString("QueueTransactionScopeAmbientCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueueTransactionScope (&apos;{0}&apos;) has completed..
        /// </summary>
        public static string QueueTransactionScopeCompleted {
            get {
                return ResourceManager.GetString("QueueTransactionScopeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueueTransactionScope (&apos;{0}&apos;) created with isolation level &apos;{1}&apos; and timeout of &apos;{2}&apos;..
        /// </summary>
        public static string QueueTransactionScopeCreated {
            get {
                return ResourceManager.GetString("QueueTransactionScopeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to register event type &apos;{0}&apos; on pipeline type &apos;{1}&apos;.  The vent type is not compatible with the supported pipeline event type &apos;{2}&apos;..
        /// </summary>
        public static string RegisteredIncompatiblePipelineEvent {
            get {
                return ResourceManager.GetString("RegisteredIncompatiblePipelineEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing message type &apos;{0}&apos; with id &apos;{1}&apos; from queue &apos;{2}&apos;..
        /// </summary>
        public static string RemoveMessageFromQueue {
            get {
                return ResourceManager.GetString("RemoveMessageFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current message.  Cannot reply..
        /// </summary>
        public static string ReplyWithoutCurrentMessage {
            get {
                return ResourceManager.GetString("ReplyWithoutCurrentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current message has no SenderIndexWorkQueueUri.  Cannot reply..
        /// </summary>
        public static string ReplyWithoutSenderInboxWorkQueueUri {
            get {
                return ResourceManager.GetString("ReplyWithoutSenderInboxWorkQueueUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have tried to requeue a message but no inbox has been configured..
        /// </summary>
        public static string RequeueWithNoInbox {
            get {
                return ResourceManager.GetString("RequeueWithNoInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required queue &apos;{0}&apos; has not been configured.  Please check your  application configuration or your code if you implemented it explicitly..
        /// </summary>
        public static string RequiredQueueMissing {
            get {
                return ResourceManager.GetString("RequiredQueueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer type &apos;{0}&apos; does not implement IKnownTypes.  Types implementing &apos;{1}&apos; cannot be added from folder &apos;{2}&apos;..
        /// </summary>
        public static string SerializerDoesNotImplementKnownTypes {
            get {
                return ResourceManager.GetString("SerializerDoesNotImplementKnownTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find serializer type specified in the application configuration file: {0}.
        /// </summary>
        public static string SerializerTypeNotFound {
            get {
                return ResourceManager.GetString("SerializerTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not registered with the serializer so it cannot be serialized.  Please use [SerialierInstance].AddKnownType to add the type before attempting to serialize or deserialize a TransportMessage containing this type in the object graph of the message property..
        /// </summary>
        public static string SerializerUnknownTypeExcption {
            get {
                return ResourceManager.GetString("SerializerUnknownTypeExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service bus instance has already been started..
        /// </summary>
        public static string ServiceBusInstanceAlreadyStarted {
            get {
                return ResourceManager.GetString("ServiceBusInstanceAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get section &apos;serviceBus&apos; from the application configuration file..
        /// </summary>
        public static string ServiceBusSectionException {
            get {
                return ResourceManager.GetString("ServiceBusSectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to start the endpoint exactly 1 type has to exist that implements IStartEndpoint but {0} were found.  The service bus for this endpoint cannot be started..
        /// </summary>
        public static string StartEndpointException {
            get {
                return ResourceManager.GetString("StartEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start endpoint type &apos;{0}&apos; implementing IStartEndpoint must have a default constructor..
        /// </summary>
        public static string StartEndpointRequiresDefaultConstructor {
            get {
                return ResourceManager.GetString("StartEndpointRequiresDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument {0} must not be empty..
        /// </summary>
        public static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find subscription manager type specified in the application configuration file: {0}.
        /// </summary>
        public static string SubscriptionManagerTypeNotFound {
            get {
                return ResourceManager.GetString("SubscriptionManagerTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [acknowledged] : message type = &apos;{0}&apos; / message id = &apos;{1}&apos;.
        /// </summary>
        public static string TraceAcknowledge {
            get {
                return ResourceManager.GetString("TraceAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [outgoing correlation id] : &apos;{0}&apos;.
        /// </summary>
        public static string TraceCorrelationIdOutgoing {
            get {
                return ResourceManager.GetString("TraceCorrelationIdOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [received correlation id] : &apos;{0}&apos;.
        /// </summary>
        public static string TraceCorrelationIdReceived {
            get {
                return ResourceManager.GetString("TraceCorrelationIdReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred transport message with id &apos;{0}&apos; has been returned to the inbox work queue..
        /// </summary>
        public static string TraceDeferredTransportMessageReturned {
            get {
                return ResourceManager.GetString("TraceDeferredTransportMessageReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding transport message type &apos;{0}&apos; with id &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string TraceForwarding {
            get {
                return ResourceManager.GetString("TraceForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [receive message state service] : transport message type &apos;{0}&apos; with id &apos;{1}&apos; has been handled and state has been removed..
        /// </summary>
        public static string TraceMessageAcknowledged {
            get {
                return ResourceManager.GetString("TraceMessageAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [receive message state service] : transport message type &apos;{0}&apos; with id &apos;{1}&apos; has already been handled..
        /// </summary>
        public static string TraceMessageHandled {
            get {
                return ResourceManager.GetString("TraceMessageHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing transport message type &apos;{0}&apos; with id &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string TracePublishing {
            get {
                return ResourceManager.GetString("TracePublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sending] : message type = &apos;{0}&apos; / queue uri = &apos;{1}&apos;.
        /// </summary>
        public static string TraceSend {
            get {
                return ResourceManager.GetString("TraceSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [transport message header (outgoing)] : {0} = {1}.
        /// </summary>
        public static string TraceTransportHeaderOutgoing {
            get {
                return ResourceManager.GetString("TraceTransportHeaderOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [transport message header (received)] : {0} = {1}.
        /// </summary>
        public static string TraceTransportHeaderReceived {
            get {
                return ResourceManager.GetString("TraceTransportHeaderReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport message with id &apos;{0}&apos; will be deferred until &apos;{1}&apos;..
        /// </summary>
        public static string TraceTransportMessageDeferred {
            get {
                return ResourceManager.GetString("TraceTransportMessageDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &apos;{0}.{1}&apos; already contains an active TransactionScope..
        /// </summary>
        public static string TransactionAlreadyStarted {
            get {
                return ResourceManager.GetString("TransactionAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &apos;{0}.{1}&apos; requires an active TransactionScope..
        /// </summary>
        public static string TransactionRequired {
            get {
                return ResourceManager.GetString("TransactionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize the transport message from queue &apos;{0}&apos;.  Exception reported: {1}.
        /// </summary>
        public static string TransportMessageDeserializationException {
            get {
                return ResourceManager.GetString("TransportMessageDeserializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportMessage with message type &apos;{0}&apos; and id &apos;{1}&apos; has been deserialized..
        /// </summary>
        public static string TransportMessageDeserialized {
            get {
                return ResourceManager.GetString("TransportMessageDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TripleDES section in the application configuration file may not have an empty value for the &apos;key&apos; attribute..
        /// </summary>
        public static string TripleDESKeyMissing {
            get {
                return ResourceManager.GetString("TripleDESKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use TripleDES cryptography you need to add the &apos;tripleDES&apos; section to the application configuration file.  Remember to add the section handler..
        /// </summary>
        public static string TripleDESSectionMissing {
            get {
                return ResourceManager.GetString("TripleDESSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is does not derive from a Message type..
        /// </summary>
        public static string TypeIsNotAMessageType {
            get {
                return ResourceManager.GetString("TypeIsNotAMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get type &apos;{0}&apos; for TypeListMessageRouteSpecification..
        /// </summary>
        public static string TypeListMessageRouteSpecificationUnknownType {
            get {
                return ResourceManager.GetString("TypeListMessageRouteSpecificationUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown message route specification &apos;{0}&apos;.  Cannot create the specification..
        /// </summary>
        public static string UnknownMessageRouteSpecification {
            get {
                return ResourceManager.GetString("UnknownMessageRouteSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected uri format &apos;{0}&apos; but received &apos;{1}&apos;..
        /// </summary>
        public static string UriFormatException {
            get {
                return ResourceManager.GetString("UriFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [publishing] : no subscribers / event message type = &apos;{0}&apos;.
        /// </summary>
        public static string WarningPublishWithoutSubscribers {
            get {
                return ResourceManager.GetString("WarningPublishWithoutSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [publishing] : no subscription manager registered / event message type = &apos;{0}&apos;.
        /// </summary>
        public static string WarningPublishWithoutSubscriptionManager {
            get {
                return ResourceManager.GetString("WarningPublishWithoutSubscriptionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inbox has been configured.  A worker requires an inbox..
        /// </summary>
        public static string WorkerRequiresInbox {
            get {
                return ResourceManager.GetString("WorkerRequiresInbox", resourceCulture);
            }
        }
    }
}
