//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Management.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name.
        /// </summary>
        public static string ColumnText_LoginName {
            get {
                return ResourceManager.GetString("ColumnText_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy HH:mm:ss.
        /// </summary>
        public static string FormatDateTime {
            get {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Image_ArrowDown {
            get {
                object obj = ResourceManager.GetObject("Image_ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Close {
            get {
                object obj = ResourceManager.GetObject("Image_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DataStore {
            get {
                object obj = ResourceManager.GetObject("Image_DataStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DataStoreDelete {
            get {
                object obj = ResourceManager.GetObject("Image_DataStoreDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DataStoreEdit {
            get {
                object obj = ResourceManager.GetObject("Image_DataStoreEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DataStoreNew {
            get {
                object obj = ResourceManager.GetObject("Image_DataStoreNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_DataStores {
            get {
                object obj = ResourceManager.GetObject("Image_DataStores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Edit {
            get {
                object obj = ResourceManager.GetObject("Image_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Exit {
            get {
                object obj = ResourceManager.GetObject("Image_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_InvertMarks {
            get {
                object obj = ResourceManager.GetObject("Image_InvertMarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_List {
            get {
                object obj = ResourceManager.GetObject("Image_List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_MarkAll {
            get {
                object obj = ResourceManager.GetObject("Image_MarkAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_New {
            get {
                object obj = ResourceManager.GetObject("Image_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Permissions {
            get {
                object obj = ResourceManager.GetObject("Image_Permissions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_PermissionsEdit {
            get {
                object obj = ResourceManager.GetObject("Image_PermissionsEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_RefreshSmall {
            get {
                object obj = ResourceManager.GetObject("Image_RefreshSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Remove {
            get {
                object obj = ResourceManager.GetObject("Image_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_Submit {
            get {
                object obj = ResourceManager.GetObject("Image_Submit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_SummaryView {
            get {
                object obj = ResourceManager.GetObject("Image_SummaryView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_SystemUser {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_SystemUserDelete {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_SystemUserEdit {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_SystemUserList {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Image_SystemUserNew {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Text_Accept {
            get {
                return ResourceManager.GetString("Text_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Text_Administration {
            get {
                return ResourceManager.GetString("Text_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data store.
        /// </summary>
        public static string Text_DataStore {
            get {
                return ResourceManager.GetString("Text_DataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data store details.
        /// </summary>
        public static string Text_DataStoreDetails {
            get {
                return ResourceManager.GetString("Text_DataStoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stores.
        /// </summary>
        public static string Text_DataStores {
            get {
                return ResourceManager.GetString("Text_DataStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Text_Decline {
            get {
                return ResourceManager.GetString("Text_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change login name.
        /// </summary>
        public static string Text_EditLoginName {
            get {
                return ResourceManager.GetString("Text_EditLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change permissions.
        /// </summary>
        public static string Text_EditPermissions {
            get {
                return ResourceManager.GetString("Text_EditPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Text_Exit {
            get {
                return ResourceManager.GetString("Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Text_File {
            get {
                return ResourceManager.GetString("Text_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert marks.
        /// </summary>
        public static string Text_InvertMarks {
            get {
                return ResourceManager.GetString("Text_InvertMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Text_List {
            get {
                return ResourceManager.GetString("Text_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string Text_Loading {
            get {
                return ResourceManager.GetString("Text_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all.
        /// </summary>
        public static string Text_MarkAll {
            get {
                return ResourceManager.GetString("Text_MarkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Text_Move {
            get {
                return ResourceManager.GetString("Text_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Store.
        /// </summary>
        public static string Text_NewDataStore {
            get {
                return ResourceManager.GetString("Text_NewDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Text_Refresh {
            get {
                return ResourceManager.GetString("Text_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Text_Remove {
            get {
                return ResourceManager.GetString("Text_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Text_Submit {
            get {
                return ResourceManager.GetString("Text_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary View.
        /// </summary>
        public static string Text_SummaryView {
            get {
                return ResourceManager.GetString("Text_SummaryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Text_Users {
            get {
                return ResourceManager.GetString("Text_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Text_View {
            get {
                return ResourceManager.GetString("Text_View", resourceCulture);
            }
        }
    }
}
